import { TbHandOff } from "react-icons/tb";
import { IoIosBeer } from "react-icons/io";
import { TbMoodCrazyHappy } from "react-icons/tb";
import { FaUserSecret } from "react-icons/fa";


export const randomCardsRompeAmistadesData = [
  {
    title: 'Yo nunca nunca',
    description: 'He robado algo a un amig@',
    type: 'neverNever',
    icon: <TbHandOff/>,
  },
  {
    title: 'Yo nunca nunca',
    description: 'He salido con el ex de un amig@',
    type: 'neverNever',
    icon: <TbHandOff/>,
  },
  {
    title: 'Yo nunca nunca',
    description: 'Le he mentido a un amig@',
    type: 'neverNever',
    icon: <TbHandOff/>,
  },
  {
    title: 'Yo nunca nunca',
    description: 'He fingido estar enfermo para no salir con mis amig@s',
    type: 'neverNever',
    icon: <TbHandOff/>,
  },
  {
    title: 'Yo nunca nunca',
    description: 'He robado dinero',
    type: 'neverNever',
    icon: <TbHandOff/>,
  },
  {
    title: 'Yo nunca nunca',
    description: 'He llorado de mentira para conseguir algo',
    type: 'neverNever',
    icon: <TbHandOff/>,
  },
  {
    title: 'Yo nunca nunca',
    description: 'He mentido jugando Yo nunca nunca',
    type: 'neverNever',
    icon: <TbHandOff/>,
  },
  {
    title: 'Yo nunca nunca',
    description: 'He dicho el nombre equivocado estando en una relacion',
    type: 'neverNever',
    icon: <TbHandOff/>,
  },
  {
    title: 'Yo nunca nunca',
    description: 'He tenido relaciones en el carro',
    type: 'neverNever',
    icon: <TbHandOff/>,
  },
  {
    title: 'Yo nunca nunca',
    description: 'He fingido un orgasmo',
    type: 'neverNever',
    icon: <TbHandOff/>,
  },
  {
    title: 'Amigos por siempre',
    description: 'Elige alguien para tomarse el mismo numero de shots',
    type: 'drink',
    icon: <IoIosBeer />,
  },
  {
    title: 'Hola',
    description: 'Solo tú bebes 1 shot',
    type: 'drink',
    icon: <IoIosBeer />,
  },
  {
    title: 'Salud',
    description: 'Tomate lo que te queda restante de tu trago',
    type: 'drink',
    icon: <IoIosBeer />,
  },
  {
    title: 'Leader',
    description: 'Todos tienen que tomarse la misma cantidad de shots que tú te tomas',
    type: 'drink',
    icon: <IoIosBeer />,
  },
  {
    title: 'Jirafa',
    description: 'La persona más alta toma 1 shot',
    type: 'drink',
    icon: <IoIosBeer />,
  },
  {
    title: 'Ajhbsdfhb',
    description: 'Di el cumpleaños de la persona de tu derecha, si no lo aciertas, tomas 1 shot',
    type: 'drink',
    icon: <IoIosBeer />,
  },
  {
    title: 'sin ideas?',
    description: 'Todos tienen 5 segundos para decir algún nombre que empiece con la letra F, el que se quede sin ideas toma 1 shot',
    type: 'drink',
    icon: <IoIosBeer />,
  },
  {
    title: 'Voy de frente',
    description: 'La persona al frente tuyo toma 1 shot',
    type: 'drink',
    icon: <IoIosBeer />,
  },
  {
    title: 'El hobbit',
    description: 'El más pequeño del grupo bebe 1 shot',
    type: 'drink',
    icon: <IoIosBeer />,
  },
  {
    title: 'Zurdo',
    description: 'Entre todos votan quién es el más feo del grupo para que tome 1 shot',
    type: 'drink',
    icon: <IoIosBeer />,
  },
  {
    title: 'RETO',
    description: 'Dale un beso a la nariz de alguien, o toma 1 shot',
    type: 'challenge',
        icon: <TbMoodCrazyHappy />,
  },
  {
    title: 'RETO',
    description: 'Di in secreto de alguien aquí, o toma 2 shots',
    type: 'challenge',
        icon: <TbMoodCrazyHappy />,
  },
  {
    title: 'RETO',
    description: 'Dale el telefono a algun amigo desbloqueado por 1 minuto, la otra persona puede hacer lo que sea',
    type: 'challenge',
        icon: <TbMoodCrazyHappy />,
  },
  {
    title: 'RETO',
    description: 'Escribele a tu ex, o toma 2 shots',
    type: 'challenge',
        icon: <TbMoodCrazyHappy />,
  },
  {
    title: 'RETO',
    description: '1 Minuto en el paraíso con la persona que elijas, o tomas 1 shot',
    type: 'challenge',
        icon: <TbMoodCrazyHappy />,
  },
  {
    title: 'RETO',
    description: 'Lee en voz alta tu ultimo mensaje, o toma 1 shot',
    type: 'challenge',
        icon: <TbMoodCrazyHappy />,
  },
  {
    title: 'RETO',
    description: 'Cuentanos un secreto de tu mejor amig@, o toma 1 shot',
    type: 'challenge',
        icon: <TbMoodCrazyHappy />,
  },
  {
    title: 'RETO',
    description: 'Huele el aliento de alguien',
    type: 'challenge',
        icon: <TbMoodCrazyHappy />,
  },
  {
    title: 'RETO',
    description: 'Subir una foto a close con tu ex Pareja, o tomas 2 shots',
    type: 'challenge',
        icon: <TbMoodCrazyHappy />,
  },
  {
    title: 'RETO',
    description: 'Dale algun alago a la persona de tu derecha',
    type: 'challenge',
        icon: <TbMoodCrazyHappy />,
  },
  {
    title: 'RETO',
    description: 'Poner de foto de perfil una foto de algun@ de tus amigos por el resto del juego',
    type: 'challenge',
        icon: <TbMoodCrazyHappy />,
  },
  {
    title: 'Cuentanos...',
    description: 'Cuentanos con quien de aquí nunca tendrías relaciones, o toma 1 shot',
    type: 'gozzip',
        icon: <FaUserSecret />,
  },
  {
    title: 'Cuentanos...',
    description: 'El lugar más extraño donde has tenido relaciones',
    type: 'gozzip',
        icon: <FaUserSecret />,
  },
  {
    title: 'Cuentanos...',
    description: 'Quien fue tu primer beso',
    type: 'gozzip',
        icon: <FaUserSecret />,
  },
  {
    title: 'Cuentanos...',
    description: 'De quien te arrepientes haber besado',
    type: 'gozzip',
        icon: <FaUserSecret />,
  },
  {
    title: 'Cuentanos...',
    description: 'Cuentanos a quien le tienes menos confianza de los presentes',
    type: 'gozzip',
        icon: <FaUserSecret />,
  },
  {
    title: 'Cuentanos...',
    description: 'Cual es tu mayor red flag',
    type: 'gozzip',
        icon: <FaUserSecret />,
  },
  {
    title: 'Cuentanos...',
    description: 'Quien crees que seria un buen novi@',
    type: 'gozzip',
        icon: <FaUserSecret />,
  },
  {
    title: 'Cuentanos...',
    description: 'Si has sentido celos de alguien de los presentes',
    type: 'gozzip',
        icon: <FaUserSecret />,
  },
  {
    title: 'Cuentanos...',
    description: 'Si el lugar estuviera incendiandose, a quien salvarias primero',
    type: 'gozzip',
        icon: <FaUserSecret />,
  },
  {
    title: 'Cuentanos...',
    description: 'Cuentanos cuando fue tu ultimo beso',
    type: 'gozzip',
        icon: <FaUserSecret />,
  },
];
