import { BsFillPatchQuestionFill } from "react-icons/bs";

export const VerdadShotHutData = [
    {
      title: 'Verdad o Shot',
      description: 'Besaría a alguien de los presentes',
      type: 'verdadShot',
      icon: <BsFillPatchQuestionFill />,
    },
    {
      title: 'Verdad o Shot',
      description: 'Cual el la peor experiencia sexual que has tenido',
      type: 'verdadShot',
      icon: <BsFillPatchQuestionFill />,
    },
    {
      title: 'Verdad o Shot',
      description: '¿Has jugado con los sentimientos de alguien alguna vez?',
      type: 'verdadShot',
      icon: <BsFillPatchQuestionFill />,
    },
    {
      title: 'Verdad o Shot',
      description: '¿Te sientes atraída a alguien de los presentes?',
      type: 'verdadShot',
      icon: <BsFillPatchQuestionFill />,
    },
    {
      title: 'Verdad o Shot',
      description: '¿Tienes algun juguete sexual?',
      type: 'verdadShot',
      icon: <BsFillPatchQuestionFill />,
    },
    {
      title: 'Verdad o Shot',
      description: '¿Tendrías relaciones con alguno de los presentes?',
      type: 'verdadShot',
      icon: <BsFillPatchQuestionFill />,
    },
    {
      title: 'Verdad o Shot',
      description: '¿Cuál ha sido tu mejor beso?',
      type: 'verdadShot',
      icon: <BsFillPatchQuestionFill />,
    },
    {
      title: 'Verdad o Shot',
      description: '¿Cuál ha sido tu peor beso?',
      type: 'verdadShot',
      icon: <BsFillPatchQuestionFill />,
    },
    {
      title: 'Verdad o Shot',
      description: '¿Regresarías con tu ex?',
      type: 'verdadShot',
      icon: <BsFillPatchQuestionFill />,
    },
    {
      title: 'Verdad o Shot',
      description: '¿Cuál es tu posición favorita en la cama?',
      type: 'verdadShot',
      icon: <BsFillPatchQuestionFill />,
    },
    {
      title: 'Verdad o Shot',
      description: '¿Cual es alguna fantasia sexual tuya?',
      type: 'verdadShot',
      icon: <BsFillPatchQuestionFill />,
    },
    {
      title: 'Verdad o Shot',
      description: '¿Alguna vez has enviado nudes?',
      type: 'verdadShot',
      icon: <BsFillPatchQuestionFill />,
    },
    {
      title: 'Verdad o Shot',
      description: '¿Cuando fue la ultima vez que tuviste relaciones sexuales?',
      type: 'verdadShot',
      icon: <BsFillPatchQuestionFill />,
    },
    {
      title: 'Verdad o Shot',
      description: 'Cuentanos el nombre de la primera persona con la que tuviste relaciones sexuales',
      type: 'verdadShot',
      icon: <BsFillPatchQuestionFill />,
    },
    {
      title: 'Verdad o Shot',
      description: '¿Cuentanos el nombre de la ultima persona con la que tuviste relaciones sexuales?',
      type: 'verdadShot',
      icon: <BsFillPatchQuestionFill />,
    },
    {
      title: 'Verdad o Shot',
      description: '¿Alguna vez has sido infiel?',
      type: 'verdadShot',
      icon: <BsFillPatchQuestionFill />,
    },
    {
      title: 'Verdad o Shot',
      description: '¿Has besado a mas de 1 persona en menos de 24 horas?',
      type: 'verdadShot',
      icon: <BsFillPatchQuestionFill />,
    },
    {
      title: 'Verdad o Shot',
      description: '¿Alguna vez has fingido un orgasmo?',
      type: 'verdadShot',
      icon: <BsFillPatchQuestionFill />,
    },
    {
      title: 'Verdad o Shot',
      description: '¿Alguna vez has mentido sobre tu vida sexual?',
      type: 'verdadShot',
      icon: <BsFillPatchQuestionFill />,
    },
    {
      title: 'Verdad o Shot',
      description: '¿que poscision no te gusta?',
      type: 'verdadShot',
      icon: <BsFillPatchQuestionFill />,
    },
    {
      title: 'Verdad o Shot',
      description: 'Escoge 3 personas para que la persona del frente tuyo diga su coger, matar y casarse',
      type: 'verdadShot',
      icon: <BsFillPatchQuestionFill />,
    },
];
