import { TbHandOff } from "react-icons/tb";

export const yoNuncaNuncaCardsData = [
    {
      title: 'Yo nunca nunca',
      description: 'He espiado a mi ex en redes sociales',
      type: 'neverNever',
      icon: <TbHandOff/>,
    },
    {
      title: 'Yo nunca nunca',
      description: 'He estado borrach@',
      type: 'neverNever',
      icon: <TbHandOff/>,
    },
    {
      title: 'Yo nunca nunca',
      description: 'Le he revisado el teléfono a mi pareja',
      type: 'neverNever',
      icon: <TbHandOff/>,
    },
    {
      title: 'Yo nunca nunca',
      description: 'He estado en la cárcel',
      type: 'neverNever',
      icon: <TbHandOff/>,
    },
    {
      title: 'Yo nunca nunca',
      description: 'He terminado a mi pareja por teléfono',
      type: 'neverNever',
      icon: <TbHandOff/>,
    },
    {
      title: 'Yo nunca nunca',
      description: 'Me he tirado un pedo delante de mi pareja',
      type: 'neverNever',
      icon: <TbHandOff/>,
    },
    {
      title: 'Yo nunca nunca',
      description: 'Me he quedado sin gasolina mientras conducía',
      type: 'neverNever',
      icon: <TbHandOff/>,
    },
    {
      title: 'Yo nunca nunca',
      description: 'He mentido en una primera cita',
      type: 'neverNever',
      icon: <TbHandOff/>,
    },
    {
      title: 'Yo nunca nunca',
      description: 'Me he quebrado un hueso',
      type: 'neverNever',
      icon: <TbHandOff/>,
    },
    {
      title: 'Yo nunca nunca',
      description: 'He vivido solo',
      type: 'neverNever',
      icon: <TbHandOff/>,
    },
    {
      title: 'Yo nunca nunca',
      description: 'He guardado el secreto de alguien de este grupo',
      type: 'neverNever',
      icon: <TbHandOff/>,
    },
    {
      title: 'Yo nunca nunca',
      description: 'He escrito cartas románticas',
      type: 'neverNever',
      icon: <TbHandOff/>,
    },
    {
      title: 'Yo nunca nunca',
      description: 'He gastado más de ₡50 Mil en una noche de fiesta',
      type: 'neverNever',
      icon: <TbHandOff/>,
    },
    {
      title: 'Yo nunca nunca',
      description: 'He dejado plantado a alguien en una cita',
      type: 'neverNever',
      icon: <TbHandOff/>,
    },
    {
      title: 'Yo nunca nunca',
      description: 'He recibido una multa',
      type: 'neverNever',
      icon: <TbHandOff/>,
    },
    {
      title: 'Yo nunca nunca',
      description: 'He estado en una pelea',
      type: 'neverNever',
      icon: <TbHandOff/>,
    },
    {
      title: 'Yo nunca nunca',
      description: 'He fumado',
      type: 'neverNever',
      icon: <TbHandOff/>,
    },
    {
      title: 'Yo nunca nunca',
      description: 'He sido infiel',
      type: 'neverNever',
      icon: <TbHandOff/>,
    },
    {
      title: 'Yo nunca nunca',
      description: 'He sido arrestado',
      type: 'neverNever',
      icon: <TbHandOff/>,
    },
    {
      title: 'Yo nunca nunca',
      description: 'He llamado/texteado a mi ex',
      type: 'neverNever',
      icon: <TbHandOff/>,
    },
    {
      title: 'Yo nunca nunca',
      description: 'He estado en una relación más de 3 años',
      type: 'neverNever',
      icon: <TbHandOff/>,
    },
    {
      title: 'Yo nunca nunca',
      description: 'He revisado el teléfono a un amigo',
      type: 'neverNever',
      icon: <TbHandOff/>,
    },
    {
      title: 'Yo nunca nunca',
      description: 'He dicho "Te amo" sin sentirlo',
      type: 'neverNever',
      icon: <TbHandOff/>,
    },
    {
      title: 'Yo nunca nunca',
      description: 'Me he buscado en Google',
      type: 'neverNever',
      icon: <TbHandOff/>,
    },
    {
      title: 'Yo nunca nunca',
      description: 'He mentido en una cita',
      type: 'neverNever',
      icon: <TbHandOff/>,
    },
    {
      title: 'Yo nunca nunca',
      description: 'Me he hecho un tatuaje',
      type: 'neverNever',
      icon: <TbHandOff/>,
    },
    {
      title: 'Yo nunca nunca',
      description: 'He conocido a alguien famoso',
      type: 'neverNever',
      icon: <TbHandOff/>,
    },
    {
      title: 'Yo nunca nunca',
      description: 'He ido al psicólogo',
      type: 'neverNever',
      icon: <TbHandOff/>,
    },
    {
      title: 'Yo nunca nunca',
      description: 'He fingido estar enfermo para no salir',
      type: 'neverNever',
      icon: <TbHandOff/>,
    },
];
