import { TbHandOff } from "react-icons/tb";
import { IoIosBeer } from "react-icons/io";
import { TbMoodCrazyHappy } from "react-icons/tb";
import { FaUserSecret } from "react-icons/fa";

export const classicCardsData = [
  {
    title: 'Yo nunca nunca',
    description: 'He sido infiel',
    type: 'neverNever',
    icon: <TbHandOff />,
  },
  {
    title: 'Yo nunca nunca',
    description: 'He estado más de 3 días sin bañarme',
    type: 'neverNever',
    icon: <TbHandOff />,
  },
  {
    title: 'Yo nunca nunca',
    description: 'He estado con alguien mayor que yo',
    type: 'neverNever',
    icon: <TbHandOff />,
  },
  {
    title: 'Yo nunca nunca',
    description: 'Me he peleado con alguien',
    type: 'neverNever',
    icon: <TbHandOff />,
  },
  {
    title: 'Yo nunca nunca',
    description: 'He robado dinero',
    type: 'neverNever',
    icon: <TbHandOff />,
  },
  {
    title: 'Yo nunca nunca',
    description: 'He llorado de mentira para conseguir algo',
    type: 'neverNever',
    icon: <TbHandOff />,
  },
  {
    title: 'Yo nunca nunca',
    description: 'He mentido jugando Yo nunca nunca',
    type: 'neverNever',
    icon: <TbHandOff />,
  },
  {
    title: 'Yo nunca nunca',
    description: 'He dicho el nombre equivocado estando en una relación',
    type: 'neverNever',
    icon: <TbHandOff />,
  },
  {
    title: 'Yo nunca nunca',
    description: 'He usado el cepillo de dientes de otra persona',
    type: 'neverNever',
    icon: <TbHandOff />,
  },
  {
    title: 'Yo nunca nunca',
    description: 'He orinado en la ducha',
    type: 'neverNever',
    icon: <TbHandOff />,
  },
  {
    title: 'Amigos por siempre',
    description: 'Elige a alguien para tomarse el mismo número de shots',
    type: 'drink',
    icon: <IoIosBeer />,
  },
  {
    title: 'Hola',
    description: 'Solo tú bebes 1 shot',
    type: 'drink',
    icon: <IoIosBeer />,
  },
  {
    title: 'Salud',
    description: 'Tómate lo que te queda restante de tu trago',
    type: 'drink',
    icon: <IoIosBeer />,
  },
  {
    title: 'Leader',
    description: 'Todos tienen que tomarse la misma cantidad de shots que tú te tomas',
    type: 'drink',
    icon: <IoIosBeer />,
  },
  {
    title: 'Jirafa',
    description: 'La persona más alta toma 1 shot',
    type: 'drink',
    icon: <IoIosBeer />,
  },
  {
    title: 'Ajhbsdfhb',
    description: 'Elige un trabalenguas, si te trabas tomas 1 shot',
    type: 'drink',
    icon: <IoIosBeer />,
  },
  {
    title: 'sin ideas?',
    description: 'Todos tienen 5 segundos para decir algún nombre que empiece con la letra F, el que se quede sin ideas toma 1 shot',
    type: 'drink',
    icon: <IoIosBeer />,
  },
  {
    title: 'Voy de frente',
    description: 'La persona al frente tuyo toma 1 shot',
    type: 'drink',
    icon: <IoIosBeer />,
  },
  {
    title: 'El hobbit',
    description: 'El más pequeño del grupo bebe 1 shot',
    type: 'drink',
    icon: <IoIosBeer />,
  },
  {
    title: 'Zurdo',
    description: 'Las personas zurdas toman 1 shot',
    type: 'drink',
    icon: <IoIosBeer />,
  },
  {
    title: 'RETO',
    description: 'Dale un beso a la nariz de alguien, o toma 1 shot',
    type: 'challenge',
    icon: <TbMoodCrazyHappy />,
  },
  {
    title: 'RETO',
    description: 'Di un secreto de alguien aquí, o toma 2 shots',
    type: 'challenge',
    icon: <TbMoodCrazyHappy />,
  },
  {
    title: 'RETO',
    description: 'Habla sin abrir la boca o toma 1 shot',
    type: 'challenge',
    icon: <TbMoodCrazyHappy />,
  },
  {
    title: 'RETO',
    description: 'Llama a alguien por teléfono y dile "Feliz cumpleaños", o toma 1 shot',
    type: 'challenge',
    icon: <TbMoodCrazyHappy />,
  },
  {
    title: 'RETO',
    description: 'Lee en voz alta tu último mensaje, o toma 1 shot',
    type: 'challenge',
    icon: <TbMoodCrazyHappy />,
  },
  {
    title: 'RETO',
    description: 'Haz 10 push-ups, o toma 1 shot',
    type: 'challenge',
    icon: <TbMoodCrazyHappy />,
  },
  {
    title: 'RETO',
    description: 'Huele el aliento de alguien',
    type: 'challenge',
    icon: <TbMoodCrazyHappy />,
  },
  {
    title: 'RETO',
    description: 'Canta 10 segundos de cualquier canción, o toma 1 shot',
    type: 'challenge',
    icon: <TbMoodCrazyHappy />,
  },
  {
    title: 'RETO',
    description: 'Dale algún halago a la persona de tu derecha',
    type: 'challenge',
    icon: <TbMoodCrazyHappy />,
  },
  {
    title: 'RETO',
    description: 'Muestra tu cuenta bancaria, o toma 1 shot',
    type: 'challenge',
    icon: <TbMoodCrazyHappy />,
  },
  {
    title: 'Cuentanos...',
    description: 'Cuéntanos el nombre de la persona que te gusta, o toma 1 shot',
    type: 'gossip',
    icon: <FaUserSecret />,
  },
  {
    title: 'Cuentanos...',
    description: 'Cuéntanos quién fue tu último beso',
    type: 'gossip',
    icon: <FaUserSecret />,
  },
  {
    title: 'Cuentanos...',
    description: 'Quién fue tu primer beso',
    type: 'gossip',
    icon: <FaUserSecret />,
  },
  {
    title: 'Cuentanos...',
    description: 'De quién te arrepientes haber besado',
    type: 'gossip',
    icon: <FaUserSecret />,
  },
  {
    title: 'Cuentanos...',
    description: 'Para ti, ¿Cuál es una red flag en alguien?',
    type: 'gossip',
    icon: <FaUserSecret />,
  },
  {
    title: 'Cuentanos...',
    description: 'Cuál es tu mayor red flag',
    type: 'gossip',
    icon: <FaUserSecret />,
  },
  {
    title: 'Cuentanos...',
    description: 'Quién crees que sería un buen novi@',
    type: 'gossip',
    icon: <FaUserSecret />,
  },
  {
    title: 'Cuentanos...',
    description: '3 datos sobre ti',
    type: 'gossip',
    icon: <FaUserSecret />,
  },
  {
    title: 'Cuentanos...',
    description: 'Si el lugar estuviera incendiándose, ¿a quién salvarías primero?',
    type: 'gossip',
    icon: <FaUserSecret />,
  },
  {
    title: 'Cuentanos...',
    description: 'Cuéntanos cuándo fue tu último beso',
    type: 'gossip',
    icon: <FaUserSecret />,
  },
];
